name: mantis_libero
channels:
  - https://aws-ml-conda.s3.us-west-2.amazonaws.com
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - pip
  - pip:
    - transformers==4.49.0
    - accelerate==1.10.1
    - diffusers==0.34.0
    - datasets==3.2.0
    - numpy==1.26.4
    - wandb==0.22.0
    - tabulate==0.9.0
    - timm==1.0.20
    - scikit-image==0.25.2
    - matplotlib==3.10.7
    - draccus==0.10.0
    - qwen-vl-utils
